### ISSUE TITLE
Running on VAST.AI

### ISSUE THREAD

**Issue by danipisca07** [ashleykleynhans/fooocus-docker#1]
Hello, i'm trying to get this running on VAST.AI but when the container start I cannot manage to get to the web interface.
To which port is the web interface exposed?
Tried both the 3001 and 8888 but they both give no response...
Thank you in advance

**Comment by ashleykleynhans** [comment]
Fooocus runs on port 3001 (via NGINX reverse proxy).
Jupyter Lab runs on port 8888 (via NGINX reverse proxy).
Unfortunately I don't support Vast.ai, only RunPod.
