### ISSUE TITLE
Missing variable "BASE_IMAGE_REPOSITORY" in docker-bake.hcl

### ISSUE THREAD

**Issue by PabloPicasso875** [ashleykleynhans/fooocus-docker#11]
PS C:\docker\fooocus-docker> docker buildx bake -f docker-bake.hcl --push
[+] Building 0.0s (1/1) FINISHED                                                                         docker:default
 => [internal] load local bake definitions                                                                         0.0s
 => => reading docker-bake.hcl 1.03kB / 1.03kB                                                                     0.0s
docker-bake.hcl:38
--------------------
  36 |         args = {
  37 |             RELEASE = "${RELEASE}"
  38 | >>>         BASE_IMAGE = "${BASE_IMAGE_REPOSITORY}:${BASE_IMAGE_VERSION}-cuda${CUDA_VERSION}-torch${TORCH_VERSION}"
  39 |             INDEX_URL = "https://download.pytorch.org/whl/cu${CU_VERSION}"
  40 |             TORCH_VERSION = "2.1.2+cu${CU_VERSION}"
--------------------
ERROR: docker-bake.hcl:38,25-46: Unknown variable; There is no variable named "BASE_IMAGE_REPOSITORY"., and 1 other diagnostic(s)
PS C:\docker\fooocus-docker>

**Comment by ashleykleynhans** [comment]
Thanks, this has now been fixed.
