### ISSUE TITLE
Passing Fooocus Command Line Arguments Through Docker?

### ISSUE THREAD

**Issue by Majoraslayer** [ashleykleynhans/fooocus-docker#12]
I'm trying to migrate from a Windows install of Fooocus to running this Docker container on Linux.  Per a guide, I had my Windows install launching from a .bat file with a couple of command line arguments.  Specifically, it ran Fooocus like this:

`D:\AI\Focus\python_embeded\python.exe -s Fooocus\entry_with_update.py --theme dark --output-path F:\Pictures\Focus --disable-in-browser --listen`

I noticed the Docker container doesn't seem to specifcally document usage for variables such as output path and theme.  How would I implement all of these options with the Docker container?

**Comment by ashleykleynhans** [comment]
You can add them by setting the `EXTRA_ARGS` environment variable that has just been added in the 2.5.0.post1 release.

**Comment by Majoraslayer** [comment]
> You can add them by setting the `EXTRA_ARGS` environment variable that has just been added in the 2.5.0.post1 release.

You're the BEST, thanks!

**Comment by Majoraslayer** [comment]
I just now was able to test this, and EXTRA_ARGS seems to be ignored.  I've tried testing just with `--theme dark` and it won't even set the theme.

EDIT: It also seems to now be ignoring the PRESET argument and defaults to "speed".

**Comment by ashleykleynhans** [comment]
How did you test it?  `EXTRA_ARGS` works fine for me, its definitely not ignored.  Ensure you're using `2.5.0.post1` and not `2.5.0`.

**Comment by Majoraslayer** [comment]
I removed the image completely and am pulling with the "latest" tag, do I need to use specific tagging to get it?

**Comment by ashleykleynhans** [comment]
`latest` tag should be fine, the hash digest is the same as for `2.5.0.post1`.
<img width="836" alt="Monosnap ashleykza:fooocus Tags | Docker Hub 2024-07-18 17-59-43" src="https://github.com/user-attachments/assets/262193af-e0bf-434a-8841-fcf4527c46cc">

**Comment by Majoraslayer** [comment]
I'm using the config below for testing purposes.  A few notes:

* 2.5.0 shows up in my browser title bar, so if post1 should be displayed there, something isn't being pulled correctly.

* The /mnt/output volume mapping here is a remnant of trying to set output-path, but I removed the argument itself for testing purposes just to see if --theme would pass correctly.  No luck yet on getting the theme to change, and the output-path argument wasn't being honored either.

* The port 3000 remapping change is intentional.

* I have the models path mapped because I have a dual boot system and want my Windows install of Fooocus to share the same models library.  This actually does work as intended, and I'm not aware of a reason it would be causing conflicts.

* I customized the mapping of the /workspace volume for portability reasons.  It seems to run this way, I'm just not able to get the custom arguments to work.  The fooocus-test directory is a completely new directory I created for testing, so it doesn't have any remnants of the previous version.

* The preset issue I had was my bad, you can ignore that from my last comment.

```
docker run -d \
    --name=fooocus-desktop \
    --restart unless-stopped \
    -p 7865:3001 \
    -p 7777:7777 \
    -p 8888:8888 \
    -p 2999:2999 \
    -e PRESET="default" \
    -e EXTRA_ARGS="--theme dark" \
    -v "/mnt/My Files/Pictures/Focus":/mnt/output \
    -v "/mnt/External A/AI/Fooocus/models":/workspace/Fooocus/models \
    -v /home/majoraslayer/dockconfig/fooocus-test:/workspace \
    --gpus all \
    ashleykza/fooocus:latest
```

**Comment by Majoraslayer** [comment]
I actually found the problem!

If you check out your start_fooocus.sh script, you have an if statement that checks if a preset has been passed with an environment variable.  You added the input for the EXTRA_ARGS variable to the default launch options without a set PRESET, but you didn't add it to the condition when PRESET is specified.  If I take out my custom PRESET variable (I was originally trying to run it as quality), EXTRA_ARGS works.

EDIT: You may also want to update the ReadMe.  It didn't seem to cause an issue, but you have an extra space before the line break `\` where you added EXTRA_ARGS in the example.  Also, I think the official Fooocus documentation doesn't use the equals sign in the output path argument ("--output-path /mnt/folder" rather than "--output-path=/mnt/folder")
