### ISSUE TITLE
Jupyter Lab Checkpoint and Lora

### ISSUE THREAD

**Issue by oliver7965** [ashleykleynhans/fooocus-docker#2]
Hello. I really appreciate your RunPod template. I'm pretty new to stable diffusion and I have a couple of issues.

First, in Jupyter Lab, I can't open the checkpoint folder for some reason.

Second, I tried installing a new Lora in the Lora folder but it doesn't appear in Fooocus. I used .safetensors.

Am I doing something wrong or is there a bug?

**Comment by ashleykleynhans** [comment]
Bug in Jupyter, log issue there, not my template:
https://github.com/jupyter-server/jupyter_server/pull/947
