### ISSUE TITLE
I need a small setup guide for beginners

### ISSUE THREAD

**Issue by teoman002** [ashleykleynhans/fooocus-docker#7]
Greetings,
would you be so kind to tell me, how to setup the client in order to connect to the remote instance of Fooocus?

Is it required to setup a ssh tunnel from `remote` to `localhost`?
Is it required to connect my `local` JupyterLab instance to `localhost:port`?

The last time I tried this repo on vast.ai, my connection was refused by ssh (explicitly NOT denied), I couldn't ping the server or get any connection to it.
Normally I would load my `public key` into the hosting platform vast.ai and tell ssh to use my `private key`.

To create a ssh tunnel I run:

`ssh -i <private_key_location> -p <port> <user@server_ip> -L <port:localhost:port>`

The server opens its ports by:

`vastai create instance x --image ashleykza/fooocus --env '-v /workspace -p 22:22 -p 7865:7865 -p 3000:3001 -p 8888:8888 -e JUPYTER_PASSWORD=Jup1t3R! --gpus all' --disk 98.36 --ssh`

**Comment by ashleykleynhans** [comment]
The Docker image sets up SSH.  The SSH public key is added using an environment variable called `PUBLIC_KEY`, I am not sure whether vast.ai does that or not, but RunPod does.
